package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type Icon struct {
	EnumDef string
	Name    string
}

// Assumes working dir of /IMG
const iconDir = "../../src/assets/icon"
const outputFile = "../../src/ui/icon_manifest.odin"

func main() {

	var icons []Icon

	err := filepath.WalkDir(iconDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			return nil
		}

		fileExt := strings.ToLower(filepath.Ext(path))

		switch fileExt {
		case ".png":
		default:
			return nil
		}

		pathRel, err := filepath.Rel(iconDir, path)
		if err != nil {
			return err
		}

		pathRel = filepath.ToSlash(pathRel)

		pathBase := filepath.Base(pathRel)
		fileName := strings.TrimSuffix(pathBase, filepath.Ext(pathBase))

		icons = append(icons, Icon{
			EnumDef: pathToEnum(pathRel),
			Name:    fileName,
		})

		return nil
	})

	if err != nil {
		panic(err)
	}

	var b strings.Builder

	b.WriteString("package ui\n\n")
	_, err = fmt.Fprintf(&b, "// Generated by IMG @ %s\n",
		time.Now().Format("02/01/2006 15:04"))

	if err != nil {
		panic(err)
	}

	b.WriteString("// DO NOT EDIT.\n\n")
	b.WriteString("Icons :: enum {\n")

	for _, icon := range icons {
		_, err = fmt.Fprintf(&b, "\t%s,\n", icon.EnumDef)

		if err != nil {
			panic(err)
		}
	}

	b.WriteString("}\n\n")

	_, err = fmt.Fprintf(&b, "Icon_names := [Icons]string{\n")

	if err != nil {
		panic(err)
	}

	for _, icon := range icons {
		_, err = fmt.Fprintf(&b, "\tIcons.%s = %q,\n", icon.EnumDef, icon.Name)

		if err != nil {
			panic(err)
		}
	}

	b.WriteString("}\n")

	if err := os.WriteFile(outputFile, []byte(b.String()), 0644); err != nil {
		panic(err)
	}
}

// pathToEnum converts a file path to a lowercase, underscore-separated enum-like string format.
func pathToEnum(path string) string {
	path = strings.TrimSuffix(path, filepath.Ext(path))
	var b strings.Builder

	for _, part := range strings.Split(path, "/") {
		b.WriteString(strings.ToLower(part))

		if part != filepath.Base(path) {
			b.WriteString("_")
		}
	}

	return b.String()
}
