package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type Icon struct {
	EnumDef string
	Name    string
}

type Dir struct {
	name  string
	count int
	icons []Icon
}

// Assumes working Dir of /IMG
const iconDir = "../../src/assets/icon"
const outputFile = "../../src/ui/icon_manifest.odin"

func main() {
	var outputDirAbs, err = filepath.Abs(outputFile)
	if err != nil {
		panic(err)
	}

	var icons []Icon
	var dirs []Dir

	err, dirs, icons = scanIcons(err, dirs, icons)
	fmt.Println(scanResult(dirs))

	err, ok := ConfirmWrite(err)
	if !ok {
		return
	}

	fmt.Print("Generating output file to: ", outputDirAbs)
	writeManifest(err, icons)
}

// ConfirmWrite asks the user if they want to continue.
func ConfirmWrite(err error) (error, bool) {
	var input string
	fmt.Println("Continue? (y/n)")
	_, err = fmt.Scanln(&input)

	if input != "y" {
		return nil, false
	}
	return err, true
}

// Recursively scans the icon directory for icons.
func scanIcons(err error, dirs []Dir, icons []Icon) (error, []Dir, []Icon) {
	err = filepath.WalkDir(iconDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			if d.Name() == "icon" {
				return nil
			}

			files, _ := os.ReadDir(path)
			var IconsInPath []Icon
			for _, file := range files {
				IconsInPath = append(IconsInPath, Icon{EnumDef: pathToEnum(file.Name()), Name: file.Name()})

				if !strings.HasSuffix(file.Name(), ".png") {
					IconsInPath = IconsInPath[:len(IconsInPath)-1]
				}
			}

			dirs = append(dirs, Dir{name: d.Name(), count: len(files), icons: IconsInPath})

			return nil
		}

		fileExt := strings.ToLower(filepath.Ext(path))

		switch fileExt {
		case ".png":
		default:
			return nil
		}

		pathRel, err := filepath.Rel(iconDir, path)
		if err != nil {
			return err
		}

		pathRel = filepath.ToSlash(pathRel)

		pathBase := filepath.Base(pathRel)
		fileName := strings.TrimSuffix(pathBase, filepath.Ext(pathBase))

		icons = append(icons, Icon{
			EnumDef: pathToEnum(pathRel),
			Name:    fileName,
		})

		return nil
	})
	return err, dirs, icons
}

// writeManifest writes the manifest file to the output directory.
func writeManifest(err error, icons []Icon) {
	var b strings.Builder

	b.WriteString("package ui\n\n")
	_, err = fmt.Fprintf(&b, "// Generated by IMG @ %s\n",
		time.Now().Format("02/01/2006 15:04"))

	if err != nil {
		panic(err)
	}

	b.WriteString("// DO NOT EDIT.\n\n")
	b.WriteString("Icons :: enum {\n")

	for _, icon := range icons {
		_, err = fmt.Fprintf(&b, "\t%s,\n", icon.EnumDef)

		if err != nil {
			panic(err)
		}
	}

	b.WriteString("}\n\n")

	_, err = fmt.Fprintf(&b, "Icon_names := [Icons]string{\n")

	if err != nil {
		panic(err)
	}

	for _, icon := range icons {
		_, err = fmt.Fprintf(&b, "\tIcons.%s = %q,\n", icon.EnumDef, icon.Name)

		if err != nil {
			panic(err)
		}
	}

	b.WriteString("}")

	if err := os.WriteFile(outputFile, []byte(b.String()), 0644); err != nil {
		panic(err)
	}
}

// pathToEnum converts a file path to a camelcase string format.
func pathToEnum(path string) string {
	path = strings.TrimSuffix(path, filepath.Ext(path))
	var b strings.Builder

	for _, part := range strings.Split(path, "/") {
		b.WriteString(strings.ToLower(part))

		if part != filepath.Base(path) {
			b.WriteString("_")
		}
	}

	return b.String()
}

func scanResult(dirs []Dir) string {
	var b strings.Builder
	var iconCount int

	for _, dirs := range dirs {
		_, err := fmt.Fprintf(&b, "- %s\n", dirs.name)

		if len(dirs.icons) == 0 {
			_, err = fmt.Fprintf(&b, "\tFound %d sub-directories\n", dirs.count)
		} else {
			_, err = fmt.Fprintf(&b, "\tFound %d icons:\n", dirs.count)
		}

		if err != nil {
			return "Something wong"
		}

		for _, icon := range dirs.icons {
			_, err = fmt.Fprintf(&b, "\t\t- %s\n", icon.Name)
			if err != nil {
				return "Something wong"
			}

			if strings.HasSuffix(icon.Name, ".png") {
				iconCount++
			}
		}
	}

	b.WriteString("\nTotal:\n")
	_, err := fmt.Fprintf(&b, "\tDirectories:     %d\n", len(dirs))
	_, err = fmt.Fprintf(&b, "\tIcons:           %d\n", iconCount)
	if err != nil {
		return "Something wong"
	}

	return b.String()
}
